### ISSUE TITLE
Mixin is not prefixed

### ISSUE THREAD

**Issue by nenadjelovac** [inuitcss/tools.responsive#3]
Same comment as with variable [here](https://github.com/inuitcss/settings.responsive/issues/3).

**Comment by florianbouvot** [comment]
+1 / ping

**Comment by csshugs** [comment]
@nenadjelovac Still keen on fixing this in pre-alpha?

**Comment by nenadjelovac** [comment]
@csshugs I don't think we should fix it in this version. So closing the issue ;)
