### ISSUE TITLE
Use global-variable-exists from Sass v3.3?

### ISSUE THREAD

**Issue by blai** [inuitcss/tools.responsive#4]
It seems if you use the `@if (global-variable-exists($inuit-responsive-settings))` instead of [this line](https://github.com/inuitcss/tools.responsive/blob/master/_tools.responsive.scss#L10) (introduced in Sass v3.3.0 http://sass-lang.com/documentation/file.SASS_CHANGELOG.html#smaller_improvements_2), you could clean up [these few lines](https://github.com/inuitcss/tools.responsive/blob/master/_tools.responsive.scss#L5-L8).

I would have submitted a pull request directly, but it wasn't clear to me which version of Sass does inuit support, so I wanted to get an agreement before submitting a change.

**Comment by csshugs** [comment]
@blai 
Thanks a lot for this idea. I didn't know about this Sass feature. I learned at least one thing today!

Nevertheless we only just fix bugs for this (pre-alpha) version of inuitcss and won't make the effort of implementing such minor improvements (although it would be far more clever than [this](https://github.com/inuitcss/tools.responsive/blob/master/_tools.responsive.scss#L5-L12)).

Anyway, thank you very much for pointing this out!

**Comment by nenadjelovac** [comment]
@csshugs would you consider raising this issue on new version of inuitcss?

**Comment by csshugs** [comment]
@nenadjelovac Yeah, thought about it. Not sure yet.
