### ISSUE TITLE
Transform to multi map mixin?

### ISSUE THREAD

**Issue by anselmh** [inuitcss/tools.responsive#7]
I read this interesting article on [making a better media query mixin in Sass using maps](http://www.zell-weekeat.com/mappy-breakpoints/) which convinced me.

Is this something to consider?

@csswizardry

**Comment by tymondesigns** [comment]
I've tweaked the media-query mixin here http://sassmeister.com/gist/ae50072626ad6416708d

less code needed if using maps!

@csswizardry would you accept a PR with this?

**Comment by nenadjelovac** [comment]
@tymondesigns this is less code indeed, and probably a bit more readable. Now, would a PR would be accepted depends on the answer about [supported sass versions](https://github.com/inuitcss/getting-started/issues/5).

**Comment by erfanimani** [comment]
+1 - map would make creating classes for specific breakpoints easier:

```
@each $alias, $condition in $breakpoint-map {
    @include media-query($alias) {
        .myclass--#{$alias} { 
            // ..
        }
    }
};
```

vs 

```
@each $breakpoint in $breakpoints {
    $alias: nth($breakpoint, 1);
    @include media-query($alias) {
        .myclass--#{$alias} { 
            // ..
        }
    }
}
```

**Comment by csshugs** [comment]
Since this repository is now officially deprecated, I close this.
If this issue is still relevant, please open a new issue in the [new repository](https://github.com/inuitcss/inuitcss).

Thanks for your time and your effort.
